### ISSUE TITLE
Acciones

### ISSUE THREAD

**Issue by yammadev** [yammadev/col-covid-19#1]
Conforme lo observado durante el proyecto, la actualización en la página de [*Datos de Gobierno*](https://www.datos.gov.co/Salud-y-Protecci-n-Social/Casos-positivos-de-COVID-19-en-Colombia/gt2j-8ykr/data) (servidor) **está disponible entre las 18:00 y las 20:00 horas cada día**, a pesar de que se publique antes a través de las cuentas oficiales, conforme lo explicado por el *Instituto Nacional de Salud* acá: 

> [...] Si bien el *Ministerio de Salud* publica la información con consolidados a una hora determinada, la carga con la información de todos los casos [...] toma mas tiempo puesto que se verifica la información de todos los casos, con el fin de establecer si ya están recuperados, fallecidos o si hubo alguna variación. Toma un poco más de tiempo la revisión y actualización del dataset completo. En este sentido, se actualizan en simultáneo la página web del INS, y el dataset [...] expuesto.

Dado que ya el proyecto está automatizado, **se requiere ejecutar el script automáticamente desde el repositorio usando acciones**.

**Comment by yammadev** [comment]
@jairoserrano ¿Alguna idea para Acciones con Python y NPM?

**Comment by jairoserrano** [comment]
ahora mismo no se bien, pero se que puedes tener unos contenedores que ejecutan cierto codigo y despliegan, no se si python sea usable acá... para mantener todo el stack con recursos "gratis" que provee github

**Comment by yammadev** [comment]
Debido a la naturaleza cambiante de los [datos](https://www.datos.gov.co/Salud-y-Protecci-n-Social/Casos-positivos-de-COVID-19-en-Colombia/gt2j-8ykr/data), es mejor revisar rápidamente previo a actualizar.  El [script](https://github.com/yammadev/col-covid-19/blob/master/update.sh) actualmente está funcionando bien para actualizar en caso de no haber ningún error en la información, por lo que no requiere más acciones.
